server.port: 8991
spring:

#  cloud:
#    gateway:
#      httpclient:
#        connect-timeout: 5000
#        response-timeout: 30s  # Set to reproduce the issue

#  cloud:
#    gateway:
#      httpclient:
#        wiretap: true

#        connect-timeout: 5000
#        response-timeout: 30s  # Set to reproduce the issue
#        pool:
#          type: fixed
#          max-connections: 500
#          max-idle-time: 20s
#          max-life-time: 60s
#          acquire-timeout: 60000

logging:
  level:
    root: INFO
    reactor.netty.http: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
    reactor.netty.core: DEBUG
    org.springframework.http: DEBUG
    io.netty.channel: DEBUG
