spring:
  config:
    activate:
      on-profile: fixed
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 60s
#        wiretap: true
        pool:
          max-idle-time: 60s
          max-connections: 500
          type: fixed
          metrics: true
          max-life-time: 60s
          max-pending-acquires: 2048
          acquire-timeout: 60000
      httpserver:
#        wiretap: true
        max-initial-line-length: 10485760
        max-header-size: 65536
        max-chunk-size: 10485760
        validateHeaders: false

reactor:
  netty:
    pool:
      leasingStrategy: fifo
    connection:
      provider: fixed
    http:
      client:
        pool:
          maxConnections: 500
          maxIdleTime: 60s
          maxLifeTime: 60s
          metrics: true