
spring:

#  cloud:
#    gateway:
#      httpclient:
#        connect-timeout: 5000
#        response-timeout: 30s  # Set to reproduce the issue
  cloud:
    gateway:
      httpclient:
        wiretap: true
#        connect-timeout: 5000
#        response-timeout: 30s  # Set to reproduce the issue
#        pool:
#          type: fixed
#          max-connections: 500
#          max-idle-time: 20s
#          max-life-time: 60s
#          acquire-timeout: 60000

logging:
  level:
    root: INFO
    reactor.netty: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.connection.pool: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG

#spring:
#  cloud:
#    gateway:
#      httpclient:
#        pool:
#          max-idle-time: 20s
#          max-life-time: 60s
#          max-connections: 2
#          type: fixed
#        connect-timeout: 5000
#        response-timeout: 15s